# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in my_rspec.gemspec
gemspec

group :development, :test do
  gem "minitest", "~> 5.16"
  gem "minitest-reporters"
  gem "pry"
  gem "rake", "~> 13.0"
  gem "retest"
  gem "rubocop", "~> 1.21"
end
