# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in my_rspec.gemspec
gemspec

gem "minitest", "~> 5.16"
gem "minitest-reporters", "~> 1.7.1"
gem "rake", "~> 13.0"
gem "rubocop", "~> 1.21"
